export const SET_CURRENT_PATH = 'SET_CURRENT_PATH';

export const GET_FOLDER_CONTENTS_FAILURE = 'GET_FOLDER_CONTENTS_FAILURE';
export const GET_FOLDER_CONTENTS_SUCCESS = 'GET_FOLDER_CONTENTS_SUCCESS';

export const OPEN_FILE_REQUEST = 'OPEN_FILE_REQUEST';
export const OPEN_FILE_FAILURE = 'OPEN_FILE_FAILURE';
export const OPEN_FILE_SUCCESS = 'OPEN_FILE_SUCCESS';

export const TOGGLE_HIDDEN_CONTENT = 'TOGGLE_HIDDEN_CONTENT';
